---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: os
# description will be included in the image's metadata
description: Zaravi's personal OS image.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: stage
    name: yazi
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y git make gcc
          - git clone https://github.com/sxyazi/yazi.git
          - cd yazi && cargo build --release --locked
          - mkdir -p /out/bin/
          - mv target/release/yazi target/release/ya /out/bin/

  - type: copy
    from: yazi
    src: /out/bin/yazi
    dest: /usr/local/bin/

  - type: copy
    from: yazi
    src: /out/bin/ya
    dest: /usr/local/bin/

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - helix
      - alacritty
      - virt-manager
      - edk2-ovmf
      - qemu
      - virt-viewer
      - starship
      - syncthing
      - atuin
      - btop
      - nu
      - rust-analyzer
      - zig
      - lldb
      - zoxide
    remove:
      # - firefox
      # - firefox-langpacks
      - kwrite
      - kfind
      - kcharselect
      - khelpcenter
      - kate
      - kate-krunner-plugin
      - kate-plugins
      - kjournald
      - kjournald-libs
      - krfb
      - krfb-libs
      # - plasma-drkonqi
      - kde-partitionmanager
      - kdebugsettings
      - plasma-systemmonitor
      - nvtop
      # - htop
      - firewall-config
      - filelight
      # - konsole

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - app.zen_browser.zen 
        - org.gnome.Loupe
        - com.github.dynobo.normcap
        - com.obsproject.Studio
        - com.usebottles.bottles
        - dev.vencord.Vesktop
        - fr.handbrake.ghb
        - io.github.dvlv.boxbuddyrs
        - io.github.ungoogled_software.ungoogled_chromium
        - md.obsidian.Obsidian
        - org.archivekeep.ArchiveKeep
        - org.gimp.GIMP
        - org.gimp.GIMP.HEIC
        - org.signal.Signal
        - org.telegram.desktop
        - org.telegram.desktop.webview
        - org.fooyin.fooyin
        - org.blender.Blender
        - net.nokyan.Resources
        - io.gitlab.liferooter.TextPieces
        - io.github.nokse22.asciidraw
        - io.github.nokse22.Exhibit
        - io.github.nate_xyz.Chromatic
        - io.bassi.Amberol
        - io.github.TheWisker.Cavasik
        - io.github.flattool.Warehouse
        - io.gitlab.theevilskeleton.Upscaler
        - app.drey.Warp
        - app.fotema.Fotema
        - app.fotema.Fotema.HEIC
        - com.cassidyjames.butler
        - com.konstantintutsch.Lock
        - com.protonvpn.www
        - com.rafaelmardojai.Blanket
        - com.system76.Popsicle
        - de.haeckerfelix.AudioSharing
        - dev.geopjr.Calligraphy
        - fr.romainvigier.MetadataCleaner
        - fm.reaper.Reaper
        - io.github.input_leap.input-leap
        - org.gnome.Papers
        - org.gnome.Showtime
        - org.gnome.baobab
        - org.kde.kdenlive
        - org.kde.krita
        - org.nickvision.tubeconverter
        - org.musicbrainz.Picard
        - org.remmina.Remmina
        - org.onlyoffice.desktopeditors
        - xyz.safeworlds.hiit
        - io.unobserved.furtherance
        
        

  - type: signing
