---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: os
# description will be included in the image's metadata
description: Zaravi's personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - helix
      - alacritty
      - steam
      - virt-install
      - virt-viewer
      - starship
    remove:
      - firefox
      - firefox-langpacks
      - kwrite
      - kfind
      - kcharselect
      - khelpcenter
      - kate
      - kjournaldbrowser
      - plasma-emojier
      - plasma-systemmonitor
      - nvtop
      - htop
      - firewall-config

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - app.zen_browser.zen 
        - org.gnome.Loupe

  - type: signing
